---
# SelahOS bootloader configuration
# Critical: --removable flag on Apple hardware survives NVRAM resets
efiBootLoader: "grub"
kernel: "/boot/vmlinuz-linux-zen"
img: "/boot/initramfs-linux-zen.img"
fallback: "/boot/initramfs-linux-zen-fallback.img"
timeout: "5"

bootloaderEntryName: "SelahOS"
kernelLine: ", with linux-zen"
fallbackKernelLine: ", with linux-zen (fallback)"

grubInstall: "grub-install"
grubMkconfig: "grub-mkconfig"
grubCfg: "/boot/grub/grub.cfg"
grubProbe: "grub-probe"
efiBootMgr: "efibootmgr"
efiBootloaderId: "SelahOS"

installEFIFallback: true
