---
defaultGroups:
    - users
    - lp
    - video
    - network
    - storage
    - wheel
    - audio
    - realtime
    - input
    - bluetooth
    - sys

autologinGroup:  autologin
sudoersGroup:    wheel

setRootPassword: false

doAutologin:     false
passwordRequirements:
    nonempty: true
    minLength: 6

userShell: /bin/bash

forbiddenNames:
    - root
    - bin
    - daemon
    - adm
    - lp
    - sync
    - shutdown
    - halt
    - mail
    - news
    - uucp
    - operator
    - games
    - gopher
    - ftp
    - man
    - nobody
    - calamares
    - selahos
